version: '3'
services:
  gotest:
    image: dedewahyuh/gotest
    container_name: gotest
    volumes:
      - ./app:/var/dbo
    ports:
      - "80:8888"
    command: /go/bin/gotest
    restart: always

